{% set data = load_setup_py_data() %}

package:
  name: nb_conda_kernels
  version: {{ data.get('version') }}

source:
  path: ../

build:
  number: 0
  script:
    - python setup.py install --single-version-externally-managed --record=record.txt

requirements:
  host:
    - python {{ python }}
    - setuptools
  run:
    - python
    - pywin32 # [win]
    - jupyter_client >=4.2

test:
  source_files:
    - setup.cfg
  requires:
    - nose
    - coverage
    - ipykernel
    - notebook
    - requests
    - mock
  commands:
    - python -m nb_conda_kernels list # [py3k]
    - nosetests nb_conda_kernels

about:
  home: https://github.com/Anaconda-Platform/nb_conda_kernels
  license: BSD 3-Clause
  license_file: LICENSE
  summary: 'Launch Jupyter kernels for any installed conda environment.'
