name: Build and test the package
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  testbed:
    defaults:
      run:
        shell: bash
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest,macos-latest,windows-latest]
    steps:
    - name: Retrieve the source code
      uses: actions/checkout@v2
    - id: conda-root
      name: Set CONDA_ROOT
      run: |
          CONDA_ROOT=$(dirname $GITHUB_WORKSPACE)/conda
          echo "::set-output name=value::$CONDA_ROOT"
          echo "::set-env name=CONDA_ROOT::$CONDA_ROOT"
          echo "CONDA_ROOT: $CONDA_ROOT"
    # Use a smaller cache entry to enable a quicker exit if we
    # have already built the testbed. Any small file will do
    - id: cache-key
      name: Retrieve cache key
      uses: actions/cache@v2
      with:
        path: ./LICENSE
        key: key-${{ matrix.os }}-${{ hashFiles('conda-recipe') }}
    - id: cache
      name: Retrieve or create the conda cache
      if: steps.cache-key.outputs.cache-hit != 'true'
      uses: actions/cache@v2
      with:
        path: ${{ steps.conda-root.outputs.value }}
        key: testbed-${{ matrix.os }}-${{ hashFiles('conda-recipe') }}
    - name: Verify or build the testbed
      if: steps.cache-key.outputs.cache-hit != 'true'
      # The argument tells the script we are in caching mode
      run: conda-recipe/build_testbed.sh
  tests:
    defaults:
      run:
        shell: bash
    runs-on: ${{ matrix.os }}
    needs: testbed
    strategy:
      fail-fast: false
      matrix:
        os: [macos-latest,ubuntu-latest,windows-latest]
        pyver: [3.6,3.7,3.8,2.7]
    steps:
    - name: Retrieve the source code
      uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - id: conda-root
      name: Set CONDA_ROOT
      run: |
          CONDA_ROOT=$(dirname $GITHUB_WORKSPACE)/conda
          echo "::set-output name=value::$CONDA_ROOT"
          echo "::set-env name=CONDA_ROOT::$CONDA_ROOT"
          echo "CONDA_ROOT: $CONDA_ROOT"
    - name: Retrieve the testbed
      uses: actions/cache@v2
      with:
        path: ${{ steps.conda-root.outputs.value }}
        key: testbed-${{ matrix.os }}-${{ hashFiles('conda-recipe') }}
    - name: Verify or build the testbed
      run: conda-recipe/build_testbed.sh
    - name: Build the package
      run: |
        mkdir -p ~/.conda
        echo $CONDA_ROOT/ext1/ext2/env/test_env1 > ~/.conda/environments.txt
        source $CONDA_ROOT/etc/profile.d/conda.sh
        conda build conda-recipe --python=${{ matrix.pyver }}
    - name: Upload to anaconda.org
      if: github.event_name == 'push'
      env:
        ANACONDA_TOKEN: ${{ secrets.ANACONDA_TOKEN }}
      run: |
        source $CONDA_ROOT/etc/profile.d/conda.sh
        conda activate
        conda install anaconda-client
        git tag describe --exact-match --tags HEAD || export LABEL="--label dev"
        anaconda --verbose --token $ANACONDA_TOKEN upload --user jupycon $LABEL $CONDA_PREFIX/conda-bld/*/*.tar.bz2 --force
 